version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: familytree
      POSTGRES_PASSWORD: PasswordFamilyTree
      POSTGRES_DB: familytree
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://familytree:PasswordFamilyTree@db:5432/familytree?schema=public"
      JWT_SECRET: "F4m1lytr33!."
      PORT: 4000
      EMAIL: "familytree@gmail.com"
      PASSWORD: "familytree"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:4000/api"
      WATCHPACK_POLLING: "true"
      NEXT_TELEMETRY_DISABLED: 1
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

volumes:
  postgres_data:
