# --- KONFIGURASI FAMILY TREE (Master Proxy) ---
server {
    listen 80;
    server_name familytree.biz.id;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name familytree.biz.id;

    ssl_certificate /etc/letsencrypt/live/familytree.biz.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/familytree.biz.id/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Next.js Hot Module Replacement
    location /_next/webpack-hmr {
        proxy_pass http://familytree_frontend:3000/_next/webpack-hmr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /ws {
        proxy_pass http://familytree_frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # Backend API Proxy
    location /api {
        proxy_pass http://familytree_backend:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Frontend Proxy
    location / {
        proxy_pass http://familytree_frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

# --- KONFIGURASI PROFILE HENDRA LATUMETEN ---
server {
    listen 80;
    server_name hendralatumeten.com;
    # Tambahkan ini agar Certbot bisa memverifikasi domain Anda
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    # Sisa trafik lainnya baru di-redirect ke HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name hendralatumeten.com;

    # Pastikan file sertifikat ini sudah di-mount ke kontainer Nginx Family Tree
    ssl_certificate /etc/letsencrypt/live/hendralatumeten.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hendralatumeten.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        # Mengarah ke IP Server dan port 3002 (Portfolio App)
        proxy_pass http://43.157.235.159:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
